### ISSUE TITLE
Can't get a running build from source

### ISSUE THREAD

**Issue by tomtastico** [xyzz/openmw-android#18]
I'm trying to make my own build to try some modifications, but can't get it running in my device.

It builds fine, and it loads the main menu. But as soon as I try to launch the game, I get this error:

```
java.lang.UnsatisfiedLinkError: No implementation found for void ui.activity.GameActivity.getPathToJni(java.lang.String, java.lang.String) (tried Java_ui_activity_GameActivity_getPathToJni and Java_ui_activity_GameActivity_getPathToJni__Ljava_lang_String_2Ljava_lang_String_2)
        at ui.activity.GameActivity.getPathToJni(Native Method)
        at ui.activity.GameActivity.onCreate(GameActivity.kt:108)
        at android.app.Activity.performCreate(Activity.java:6713)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2632)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2740)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6144)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

It seems this getPathToJni is related to TES3MP. I didn't find it anywhere in OpenMW-Android source.

Am I missing something?

**Comment by xyzz** [comment]
You should paste more of the log. getPathToJni is implemented in https://github.com/OpenMW/openmw/blob/deeccb278366ffa4707b4c034d987b843c867151/components/files/androidpath.cpp#L18

**Comment by tomtastico** [comment]
After trying again from scartch ,this time targeting arm64, it worked! Might be related to arm vs arm64 for the device I'm trying to run on (Oculus Quest). But anyway it's solved.
